# Generated by Django 5.2.1 on 2025-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0002_subscriber_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(verbose_name='Observations')),
                ('date', models.DateField(verbose_name='Date de la coupure')),
                ('heure_debut', models.CharField(max_length=10, verbose_name='Heure de début')),
                ('heure_fin', models.CharField(max_length=10, verbose_name='Heure de fin')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('subscribers_notified', models.ManyToManyField(blank=True, related_name='coupures_notified', to='newsletter.subscriber', verbose_name='Abonnés notifiés')),
            ],
            options={
                'verbose_name': 'Coupure programmée',
                'verbose_name_plural': 'Coupures programmées',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
