#version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:10000 EneoNewsletter.wsgi
    ports:
      - "10000:10000"
    env_file: ".env"
    depends_on:
      - redis
#      - db

    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  celery:
    build: .
    command: celery -A EneoNewsletter worker --loglevel=info
    env_file: ".env"
    depends_on:
      - redis
#      - db
    restart: unless-stopped
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A EneoNewsletter beat --loglevel=info
    env_file: ".env"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    env_file: ".env"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data



#  db:
#    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"

volumes:
#  postgres_data:
  redis_data:
  static_volume:
  media_volume:
