# Generated by Django 4.2.11 on 2025-05-22 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sending', 'Envoi en cours'), ('sent', 'Envoyé')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de désinscription')),
                ('token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Jeton de sécurité')),
            ],
            options={
                'verbose_name': 'Abonné',
                'verbose_name_plural': 'Abonnés',
                'ordering': ['-subscribed_date'],
            },
        ),
    ]
