# Generated by Django 4.2.11 on 2025-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
    ]
