# Generated by Django 5.2.1 on 2025-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Quartier'),
        ),
    ]
